import type { CollectionConfig } from 'payload';

import { SlugField } from '@/fields/slug';

export const Pages: CollectionConfig = {
  slug: 'pages',
  admin: {
    useAsTitle: 'title',
    defaultColumns: ['title', 'slug', 'updatedAt'],
  },
  fields: [
    {
      required: true,
      name: 'title',
      type: 'text',
      label: 'Title',
    },
    // TODO validation against page not generated by CMS
    ...SlugField({
      overrides: {
        slugOverrides: {
          admin: {
            description: 'Page with "home" slug will be used as homepage',
          },
        },
      },
    }),
    {
      name: 'publishedAt',
      type: 'date',
      admin: {
        position: 'sidebar',
      },
    },
  ],
  versions: {
    drafts: {
      autosave: {
        interval: 375,
      },
    },
    maxPerDoc: 20,
  },
};
